using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace MonoMod.Core.Interop
{
    internal static unsafe partial class CoreCLR
    {
        [SuppressMessage("Performance", "CA1812: Avoid uninstantiated internal classes",
            Justification = "It must be non-static to be able to inherit others, as it does. This allows the Core*Runtime types " +
            "to each reference exactly the version they represent, and the compiler automatically resolves the correct one without " +
            "needing duplicates.")]
        [SuppressMessage("Performance", "CA1852", Justification = "This type will be derived for .NET 12.")]
        public class V110 : V100
        {
            public new static class ICorJitInfoVtable
            {
                // This listing is generated by build/extract-corjit-vtable.
                //
                // src/coreclr/inc/corinfo.h:2131
                // class ICorStaticInfo
                // 00: bool isIntrinsic(CORINFO_METHOD_HANDLE)
                // 01: bool canValueClassInstancePointerEscape(CORINFO_METHOD_HANDLE)
                // 02: bool notifyMethodInfoUsage(CORINFO_METHOD_HANDLE)
                // 03: uint32_t getMethodAttribs(CORINFO_METHOD_HANDLE)
                // 04: void setMethodAttribs(CORINFO_METHOD_HANDLE, CorInfoMethodRuntimeFlags)
                // 05: void getMethodSig(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *, CORINFO_CLASS_HANDLE)
                // 06: bool getMethodInfo(CORINFO_METHOD_HANDLE, CORINFO_METHOD_INFO *, CORINFO_CONTEXT_HANDLE)
                // 07: bool haveSameMethodDefinition(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 08: CORINFO_CLASS_HANDLE getTypeDefinition(CORINFO_CLASS_HANDLE)
                // 09: CorInfoInline canInline(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 0A: void beginInlining(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 0B: void reportInliningDecision(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, CorInfoInline, const char *)
                // 0C: bool canTailCall(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, bool)
                // 0D: void reportTailCallDecision(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, bool, CorInfoTailCall, const char *)
                // 0E: void getEHinfo(CORINFO_METHOD_HANDLE, unsigned int, CORINFO_EH_CLAUSE *)
                // 0F: CORINFO_CLASS_HANDLE getMethodClass(CORINFO_METHOD_HANDLE)
                // 10: void getMethodVTableOffset(CORINFO_METHOD_HANDLE, unsigned int *, unsigned int *, bool *)
                // 11: bool resolveVirtualMethod(CORINFO_DEVIRTUALIZATION_INFO *)
                // 12: CORINFO_METHOD_HANDLE getAsyncOtherVariant(CORINFO_METHOD_HANDLE, bool *)
                // 13: CORINFO_CLASS_HANDLE getDefaultComparerClass(CORINFO_CLASS_HANDLE)
                // 14: CORINFO_CLASS_HANDLE getDefaultEqualityComparerClass(CORINFO_CLASS_HANDLE)
                // 15: CORINFO_CLASS_HANDLE getSZArrayHelperEnumeratorClass(CORINFO_CLASS_HANDLE)
                // 16: void expandRawHandleIntrinsic(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_GENERICHANDLE_RESULT *)
                // 17: bool isIntrinsicType(CORINFO_CLASS_HANDLE)
                // 18: CorInfoCallConvExtension getUnmanagedCallConv(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *, bool *)
                // 19: bool pInvokeMarshalingRequired(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *)
                // 1A: bool satisfiesMethodConstraints(CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE)
                // 1B: void methodMustBeLoadedBeforeCodeIsRun(CORINFO_METHOD_HANDLE)
                // 1C: void getGSCookie(GSCookie *, GSCookie **)
                // 1D: void setPatchpointInfo(PatchpointInfo *)
                // 1E: PatchpointInfo * getOSRInfo(unsigned int *)
                // 1F: void resolveToken(CORINFO_RESOLVED_TOKEN *)
                // 20: void findSig(CORINFO_MODULE_HANDLE, unsigned int, CORINFO_CONTEXT_HANDLE, CORINFO_SIG_INFO *)
                // 21: void findCallSiteSig(CORINFO_MODULE_HANDLE, unsigned int, CORINFO_CONTEXT_HANDLE, CORINFO_SIG_INFO *)
                // 22: CORINFO_CLASS_HANDLE getTokenTypeAsHandle(CORINFO_RESOLVED_TOKEN *)
                // 23: int getStringLiteral(CORINFO_MODULE_HANDLE, unsigned int, char16_t *, int, int)
                // 24: size_t printObjectDescription(CORINFO_OBJECT_HANDLE, char *, size_t, size_t *)
                // 25: CorInfoType asCorInfoType(CORINFO_CLASS_HANDLE)
                // 26: const char * getClassNameFromMetadata(CORINFO_CLASS_HANDLE, const char **)
                // 27: CORINFO_CLASS_HANDLE getTypeInstantiationArgument(CORINFO_CLASS_HANDLE, unsigned int)
                // 28: CORINFO_CLASS_HANDLE getMethodInstantiationArgument(CORINFO_METHOD_HANDLE, unsigned int)
                // 29: size_t printClassName(CORINFO_CLASS_HANDLE, char *, size_t, size_t *)
                // 2A: bool isValueClass(CORINFO_CLASS_HANDLE)
                // 2B: uint32_t getClassAttribs(CORINFO_CLASS_HANDLE)
                // 2C: const char * getClassAssemblyName(CORINFO_CLASS_HANDLE)
                // 2D: void * LongLifetimeMalloc(size_t)
                // 2E: void LongLifetimeFree(void *)
                // 2F: bool getIsClassInitedFlagAddress(CORINFO_CLASS_HANDLE, CORINFO_CONST_LOOKUP *, int *)
                // 30: void * getClassStaticDynamicInfo(CORINFO_CLASS_HANDLE)
                // 31: void * getClassThreadStaticDynamicInfo(CORINFO_CLASS_HANDLE)
                // 32: bool getStaticBaseAddress(CORINFO_CLASS_HANDLE, bool, CORINFO_CONST_LOOKUP *)
                // 33: unsigned int getClassSize(CORINFO_CLASS_HANDLE)
                // 34: unsigned int getHeapClassSize(CORINFO_CLASS_HANDLE)
                // 35: bool canAllocateOnStack(CORINFO_CLASS_HANDLE)
                // 36: unsigned int getClassAlignmentRequirement(CORINFO_CLASS_HANDLE, bool)
                // 37: unsigned int getClassGClayout(CORINFO_CLASS_HANDLE, uint8_t *)
                // 38: unsigned int getClassNumInstanceFields(CORINFO_CLASS_HANDLE)
                // 39: CORINFO_FIELD_HANDLE getFieldInClass(CORINFO_CLASS_HANDLE, int32_t)
                // 3A: GetTypeLayoutResult getTypeLayout(CORINFO_CLASS_HANDLE, CORINFO_TYPE_LAYOUT_NODE *, size_t *)
                // 3B: bool checkMethodModifier(CORINFO_METHOD_HANDLE, const char *, bool)
                // 3C: CorInfoHelpFunc getNewHelper(CORINFO_CLASS_HANDLE, bool *)
                // 3D: CorInfoHelpFunc getNewArrHelper(CORINFO_CLASS_HANDLE)
                // 3E: CorInfoHelpFunc getCastingHelper(CORINFO_RESOLVED_TOKEN *, bool)
                // 3F: CorInfoHelpFunc getSharedCCtorHelper(CORINFO_CLASS_HANDLE)
                // 40: CORINFO_CLASS_HANDLE getTypeForBox(CORINFO_CLASS_HANDLE)
                // 41: CorInfoHelpFunc getBoxHelper(CORINFO_CLASS_HANDLE)
                // 42: CorInfoHelpFunc getUnBoxHelper(CORINFO_CLASS_HANDLE)
                // 43: CORINFO_OBJECT_HANDLE getRuntimeTypePointer(CORINFO_CLASS_HANDLE)
                // 44: bool isObjectImmutable(CORINFO_OBJECT_HANDLE)
                // 45: bool getStringChar(CORINFO_OBJECT_HANDLE, int, uint16_t *)
                // 46: CORINFO_CLASS_HANDLE getObjectType(CORINFO_OBJECT_HANDLE)
                // 47: bool getReadyToRunHelper(CORINFO_RESOLVED_TOKEN *, CorInfoHelpFunc, CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *)
                // 48: void getReadyToRunDelegateCtorHelper(CORINFO_RESOLVED_TOKEN *, mdToken, CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_LOOKUP *)
                // 49: CorInfoInitClassResult initClass(CORINFO_FIELD_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_CONTEXT_HANDLE)
                // 4A: void classMustBeLoadedBeforeCodeIsRun(CORINFO_CLASS_HANDLE)
                // 4B: CORINFO_CLASS_HANDLE getBuiltinClass(CorInfoClassId)
                // 4C: CorInfoType getTypeForPrimitiveValueClass(CORINFO_CLASS_HANDLE)
                // 4D: CorInfoType getTypeForPrimitiveNumericClass(CORINFO_CLASS_HANDLE)
                // 4E: bool canCast(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 4F: TypeCompareState compareTypesForCast(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 50: TypeCompareState compareTypesForEquality(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 51: bool isMoreSpecificType(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 52: bool isExactType(CORINFO_CLASS_HANDLE)
                // 53: TypeCompareState isGenericType(CORINFO_CLASS_HANDLE)
                // 54: TypeCompareState isNullableType(CORINFO_CLASS_HANDLE)
                // 55: TypeCompareState isEnum(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE *)
                // 56: CORINFO_CLASS_HANDLE getParentType(CORINFO_CLASS_HANDLE)
                // 57: CorInfoType getChildType(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE *)
                // 58: bool isSDArray(CORINFO_CLASS_HANDLE)
                // 59: unsigned int getArrayRank(CORINFO_CLASS_HANDLE)
                // 5A: CorInfoArrayIntrinsic getArrayIntrinsicID(CORINFO_METHOD_HANDLE)
                // 5B: void * getArrayInitializationData(CORINFO_FIELD_HANDLE, uint32_t)
                // 5C: CorInfoIsAccessAllowedResult canAccessClass(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_HELPER_DESC *)
                // 5D: size_t printFieldName(CORINFO_FIELD_HANDLE, char *, size_t, size_t *)
                // 5E: CORINFO_CLASS_HANDLE getFieldClass(CORINFO_FIELD_HANDLE)
                // 5F: CorInfoType getFieldType(CORINFO_FIELD_HANDLE, CORINFO_CLASS_HANDLE *, CORINFO_CLASS_HANDLE)
                // 60: unsigned int getFieldOffset(CORINFO_FIELD_HANDLE)
                // 61: void getFieldInfo(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_ACCESS_FLAGS, CORINFO_FIELD_INFO *)
                // 62: uint32_t getThreadLocalFieldInfo(CORINFO_FIELD_HANDLE, bool)
                // 63: void getThreadLocalStaticBlocksInfo(CORINFO_THREAD_STATIC_BLOCKS_INFO *)
                // 64: void getThreadLocalStaticInfo_NativeAOT(CORINFO_THREAD_STATIC_INFO_NATIVEAOT *)
                // 65: bool isFieldStatic(CORINFO_FIELD_HANDLE)
                // 66: int getArrayOrStringLength(CORINFO_OBJECT_HANDLE)
                // 67: void getBoundaries(CORINFO_METHOD_HANDLE, unsigned int *, uint32_t **, ICorDebugInfo::BoundaryTypes *)
                // 68: void setBoundaries(CORINFO_METHOD_HANDLE, uint32_t, ICorDebugInfo::OffsetMapping *)
                // 69: void getVars(CORINFO_METHOD_HANDLE, uint32_t *, ICorDebugInfo::ILVarInfo **, bool *)
                // 6A: void setVars(CORINFO_METHOD_HANDLE, uint32_t, ICorDebugInfo::NativeVarInfo *)
                // 6B: void reportRichMappings(ICorDebugInfo::InlineTreeNode *, uint32_t, ICorDebugInfo::RichOffsetMapping *, uint32_t)
                // 6C: void reportAsyncDebugInfo(ICorDebugInfo::AsyncInfo *, ICorDebugInfo::AsyncSuspensionPoint *, ICorDebugInfo::AsyncContinuationVarInfo *, uint32_t)
                // 6D: void reportMetadata(const char *, const void *, size_t)
                // 6E: void * allocateArray(size_t)
                // 6F: void freeArray(void *)
                // 70: CORINFO_ARG_LIST_HANDLE getArgNext(CORINFO_ARG_LIST_HANDLE)
                // 71: CorInfoTypeWithMod getArgType(CORINFO_SIG_INFO *, CORINFO_ARG_LIST_HANDLE, CORINFO_CLASS_HANDLE *)
                // 72: int getExactClasses(CORINFO_CLASS_HANDLE, int, CORINFO_CLASS_HANDLE *)
                // 73: CORINFO_CLASS_HANDLE getArgClass(CORINFO_SIG_INFO *, CORINFO_ARG_LIST_HANDLE)
                // 74: CorInfoHFAElemType getHFAType(CORINFO_CLASS_HANDLE)
                // 75: bool runWithErrorTrap(errorTrapFunction, void *)
                // 76: bool runWithSPMIErrorTrap(errorTrapFunction, void *)
                // 77: void getEEInfo(CORINFO_EE_INFO *)
                // 78: void getAsyncInfo(CORINFO_ASYNC_INFO *)
                // 79: CORINFO_METHOD_HANDLE getAwaitReturnCall(CORINFO_METHOD_HANDLE, CORINFO_CONTEXT_HANDLE *, CORINFO_LOOKUP *)
                // 7A: CORINFO_METHOD_HANDLE getAwaitAwaiterInContinuationCall(CORINFO_METHOD_HANDLE, CORINFO_RESOLVED_TOKEN *, bool, CORINFO_CONTEXT_HANDLE *, CORINFO_LOOKUP *)
                // 7B: mdMethodDef getMethodDefFromMethod(CORINFO_METHOD_HANDLE)
                // 7C: size_t printMethodName(CORINFO_METHOD_HANDLE, char *, size_t, size_t *)
                // 7D: const char * getMethodNameFromMetadata(CORINFO_METHOD_HANDLE, const char **, const char **, const char **, size_t)
                // 7E: unsigned int getMethodHash(CORINFO_METHOD_HANDLE)
                // 7F: bool getSystemVAmd64PassStructInRegisterDescriptor(CORINFO_CLASS_HANDLE, SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR *)
                // 80: void getSwiftLowering(CORINFO_CLASS_HANDLE, CORINFO_SWIFT_LOWERING *)
                // 81: void getFpStructLowering(CORINFO_CLASS_HANDLE, CORINFO_FPSTRUCT_LOWERING *)
                // 82: CorInfoWasmType getWasmLowering(CORINFO_CLASS_HANDLE)
                // 83: uint32_t getAddressAlignment(void *)
                // 84: void getWasmWellKnownGlobals(CORINFO_WASM_WELLKNOWN_GLOBALS *)
                //
                // src/coreclr/inc/corinfo.h:3283
                // class ICorDynamicInfo
                // 85: uint32_t getThreadTLSIndex(void **)
                // 86: int32_t * getAddrOfCaptureThreadGlobal(void **)
                // 87: void getHelperFtn(CorInfoHelpFunc, CORINFO_CONST_LOOKUP *, CORINFO_METHOD_HANDLE *)
                // 88: void getFunctionEntryPoint(CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *, CORINFO_ACCESS_FLAGS)
                // 89: void getFunctionFixedEntryPoint(CORINFO_METHOD_HANDLE, bool, CORINFO_CONST_LOOKUP *)
                // 8A: CORINFO_MODULE_HANDLE embedModuleHandle(CORINFO_MODULE_HANDLE, void **)
                // 8B: CORINFO_CLASS_HANDLE embedClassHandle(CORINFO_CLASS_HANDLE, void **)
                // 8C: CORINFO_METHOD_HANDLE embedMethodHandle(CORINFO_METHOD_HANDLE, void **)
                // 8D: CORINFO_FIELD_HANDLE embedFieldHandle(CORINFO_FIELD_HANDLE, void **)
                // 8E: void embedGenericHandle(CORINFO_RESOLVED_TOKEN *, bool, CORINFO_METHOD_HANDLE, CORINFO_GENERICHANDLE_RESULT *)
                // 8F: void getLocationOfThisType(CORINFO_METHOD_HANDLE, CORINFO_LOOKUP_KIND *)
                // 90: void getAddressOfPInvokeTarget(CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *)
                // 91: void * GetCookieForPInvokeCalliSig(CORINFO_SIG_INFO *, void **)
                // 92: void * GetCookieForInterpreterCalliSig(CORINFO_SIG_INFO *)
                // 93: CORINFO_JUST_MY_CODE_HANDLE getJustMyCodeHandle(CORINFO_METHOD_HANDLE, CORINFO_JUST_MY_CODE_HANDLE **)
                // 94: void GetProfilingHandle(bool *, void **, bool *)
                // 95: void getCallInfo(CORINFO_RESOLVED_TOKEN *, CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_CALLINFO_FLAGS, CORINFO_CALL_INFO *)
                // 96: bool getStaticFieldContent(CORINFO_FIELD_HANDLE, uint8_t *, int, int, bool)
                // 97: bool getObjectContent(CORINFO_OBJECT_HANDLE, uint8_t *, int, int)
                // 98: CORINFO_CLASS_HANDLE getStaticFieldCurrentClass(CORINFO_FIELD_HANDLE, bool *)
                // 99: CORINFO_VARARGS_HANDLE getVarArgsHandle(CORINFO_SIG_INFO *, CORINFO_METHOD_HANDLE, void **)
                // 9A: InfoAccessType constructStringLiteral(CORINFO_MODULE_HANDLE, mdToken, void **)
                // 9B: InfoAccessType emptyStringLiteral(void **)
                // 9C: uint32_t getFieldThreadLocalStoreID(CORINFO_FIELD_HANDLE, void **)
                // 9D: CORINFO_METHOD_HANDLE GetDelegateCtor(CORINFO_METHOD_HANDLE, CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE, DelegateCtorArgs *)
                // 9E: void MethodCompileComplete(CORINFO_METHOD_HANDLE)
                // 9F: bool getTailCallHelpers(CORINFO_RESOLVED_TOKEN *, CORINFO_SIG_INFO *, CORINFO_GET_TAILCALL_HELPERS_FLAGS, CORINFO_TAILCALL_HELPERS *)
                // A0: CORINFO_METHOD_HANDLE getAsyncResumptionStub(void **)
                // A1: CORINFO_CLASS_HANDLE getContinuationType(size_t, bool *, size_t)
                // A2: bool convertPInvokeCalliToCall(CORINFO_RESOLVED_TOKEN *, bool)
                // A3: bool notifyInstructionSetUsage(CORINFO_InstructionSet, bool)
                // A4: void updateEntryPointForTailCall(CORINFO_CONST_LOOKUP *)
                // A5: CORINFO_WASM_TYPE_SYMBOL_HANDLE getWasmTypeSymbol(CorInfoWasmType *, size_t)
                // A6: CORINFO_METHOD_HANDLE getSpecialCopyHelper(CORINFO_CLASS_HANDLE)
                //
                // src/coreclr/inc/corjit.h:171
                // class ICorJitInfo
                // A7: void allocMem(AllocMemArgs *)
                public const int AllocMemIndex = 0xA7;
                // A8: void reserveUnwindInfo(bool, bool, uint32_t)
                // A9: void allocUnwindInfo(uint8_t *, uint8_t *, uint32_t, uint32_t, uint32_t, uint8_t *, CorJitFuncKind)
                // AA: void * allocGCInfo(size_t)
                // AB: void setEHcount(unsigned int)
                // AC: void setEHinfo(unsigned int, const CORINFO_EH_CLAUSE *)
                // AD: bool logMsg(unsigned int, const char *, int)
                // AE: int doAssert(const char *, int, const char *)
                // AF: void reportFatalError(CorJitResult)
                // B0: JITINTERFACE_HRESULT getPgoInstrumentationResults(CORINFO_METHOD_HANDLE, PgoInstrumentationSchema **, uint32_t *, uint8_t **, PgoSource *, bool *)
                // B1: JITINTERFACE_HRESULT allocPgoInstrumentationBySchema(CORINFO_METHOD_HANDLE, PgoInstrumentationSchema *, uint32_t, uint8_t **)
                // B2: void recordCallSite(uint32_t, CORINFO_SIG_INFO *, CORINFO_METHOD_HANDLE)
                // B3: void recordWasmManagedCallSig(CORINFO_SIG_INFO *)
                // B4: void recordRelocation(void *, void *, void *, CorInfoReloc, int32_t)
                // B5: CorInfoReloc getRelocTypeHint(void *)
                // B6: uint32_t getExpectedTargetArchitecture()
                // B7: uint32_t getJitFlags(CORJIT_FLAGS *, uint32_t)

                public const int TotalVtableCount = 0xB8;
            }

            // src/coreclr/inc/corjit.h AllocMemChunk / AllocMemArgs
            // AllocMemArgs is a chunk list (hot/cold/readonly), not the older flat layout.
            [Flags]
            public enum CorJitAllocMemFlag : uint
            {
                HotCode = 1,
                ColdCode = 2,
                ReadonlyData = 4,
                HasPointersToCode = 8,
            }

            [StructLayout(LayoutKind.Sequential)]
            public struct AllocMemChunk
            {
                public uint alignment;
                public uint size;
                public CorJitAllocMemFlag flags;
                public IntPtr block;
                public IntPtr blockRW;
            }

            [StructLayout(LayoutKind.Sequential)]
            public new struct AllocMemArgs
            {
                public AllocMemChunk* chunks;
                public uint chunksCount;
                public uint xcptnsCount;
            }

            [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
            public new delegate void AllocMemDelegate(
                IntPtr thisPtr, // ICorJitInfo*
                AllocMemArgs* args
            );

            public new readonly struct InvokeAllocMemPtr
            {
                private readonly IntPtr methodPtr;

                public InvokeAllocMemPtr(delegate*<IntPtr, IntPtr, AllocMemArgs*, void> ptr)
                {
                    methodPtr = (IntPtr)ptr;
                }

                public delegate*<IntPtr, IntPtr, AllocMemArgs*, void> InvokeAllocMem
                    => (delegate*<IntPtr, IntPtr, AllocMemArgs*, void>)methodPtr;
            }

            public static new InvokeAllocMemPtr InvokeAllocMemFn => new(&InvokeAllocMem);

            public static new void InvokeAllocMem(
                IntPtr functionPtr,
                IntPtr thisPtr,
                AllocMemArgs* args)
            {
                if (functionPtr == IntPtr.Zero)
                    return;

                var fnPtr = (delegate* unmanaged[Thiscall]<IntPtr, AllocMemArgs*, void>)functionPtr;
                fnPtr(thisPtr, args);
            }
        }
    }
}
