using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace MonoMod.Core.Interop
{
    internal static unsafe partial class CoreCLR
    {
        [SuppressMessage("Performance", "CA1812: Avoid uninstantiated internal classes",
            Justification = "It must be non-static to be able to inherit others, as it does. This allows the Core*Runtime types " +
            "to each reference exactly the version they represent, and the compiler automatically resolves the correct one without " +
            "needing duplicates.")]
        [SuppressMessage("Performance", "CA1852", Justification = "This type will be derived for .NET 12.")]
        public class V110 : V100
        {
            public new static class ICorJitInfoVtable
            {
                // This listing is generated by build/extract-corjit-vtable.
                //
                // src\coreclr\inc\corinfo.h
                // class ICorStaticInfo
                // 00: bool isIntrinsic(CORINFO_METHOD_HANDLE)
                // 01: bool notifyMethodInfoUsage(CORINFO_METHOD_HANDLE)
                // 02: uint32_t getMethodAttribs(CORINFO_METHOD_HANDLE)
                // 03: void setMethodAttribs(CORINFO_METHOD_HANDLE, CorInfoMethodRuntimeFlags)
                // 04: void getMethodSig(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *, CORINFO_CLASS_HANDLE)
                // 05: bool getMethodInfo(CORINFO_METHOD_HANDLE, CORINFO_METHOD_INFO *, CORINFO_CONTEXT_HANDLE)
                // 06: bool haveSameMethodDefinition(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 07: CORINFO_CLASS_HANDLE getTypeDefinition(CORINFO_CLASS_HANDLE)
                // 08: CorInfoInline canInline(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 09: void beginInlining(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE)
                // 0A: void reportInliningDecision(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, CorInfoInline, const char *)
                // 0B: bool canTailCall(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, bool)
                // 0C: void reportTailCallDecision(CORINFO_METHOD_HANDLE, CORINFO_METHOD_HANDLE, bool, CorInfoTailCall, const char *)
                // 0D: void getEHinfo(CORINFO_METHOD_HANDLE, unsigned int, CORINFO_EH_CLAUSE *)
                // 0E: CORINFO_CLASS_HANDLE getMethodClass(CORINFO_METHOD_HANDLE)
                // 0F: void getMethodVTableOffset(CORINFO_METHOD_HANDLE, unsigned int *, unsigned int *, bool *)
                // 10: bool resolveVirtualMethod(CORINFO_DEVIRTUALIZATION_INFO *)
                // 11: CORINFO_METHOD_HANDLE getAsyncOtherVariant(CORINFO_METHOD_HANDLE, bool *)
                // 12: CORINFO_CLASS_HANDLE getDefaultComparerClass(CORINFO_CLASS_HANDLE)
                // 13: CORINFO_CLASS_HANDLE getDefaultEqualityComparerClass(CORINFO_CLASS_HANDLE)
                // 14: CORINFO_CLASS_HANDLE getSZArrayHelperEnumeratorClass(CORINFO_CLASS_HANDLE)
                // 15: void expandRawHandleIntrinsic(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_GENERICHANDLE_RESULT *)
                // 16: bool isIntrinsicType(CORINFO_CLASS_HANDLE)
                // 17: CorInfoCallConvExtension getUnmanagedCallConv(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *, bool *)
                // 18: bool pInvokeMarshalingRequired(CORINFO_METHOD_HANDLE, CORINFO_SIG_INFO *)
                // 19: bool satisfiesMethodConstraints(CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE)
                // 1A: void methodMustBeLoadedBeforeCodeIsRun(CORINFO_METHOD_HANDLE)
                // 1B: void getGSCookie(GSCookie *, GSCookie **)
                // 1C: void setPatchpointInfo(PatchpointInfo *)
                // 1D: PatchpointInfo * getOSRInfo(unsigned int *)
                // 1E: void resolveToken(CORINFO_RESOLVED_TOKEN *)
                // 1F: void findSig(CORINFO_MODULE_HANDLE, unsigned int, CORINFO_CONTEXT_HANDLE, CORINFO_SIG_INFO *)
                // 20: void findCallSiteSig(CORINFO_MODULE_HANDLE, unsigned int, CORINFO_CONTEXT_HANDLE, CORINFO_SIG_INFO *)
                // 21: CORINFO_CLASS_HANDLE getTokenTypeAsHandle(CORINFO_RESOLVED_TOKEN *)
                // 22: int getStringLiteral(CORINFO_MODULE_HANDLE, unsigned int, char16_t *, int, int)
                // 23: size_t printObjectDescription(CORINFO_OBJECT_HANDLE, char *, size_t, size_t *)
                // 24: CorInfoType asCorInfoType(CORINFO_CLASS_HANDLE)
                // 25: const char * getClassNameFromMetadata(CORINFO_CLASS_HANDLE, const char **)
                // 26: CORINFO_CLASS_HANDLE getTypeInstantiationArgument(CORINFO_CLASS_HANDLE, unsigned int)
                // 27: CORINFO_CLASS_HANDLE getMethodInstantiationArgument(CORINFO_METHOD_HANDLE, unsigned int)
                // 28: size_t printClassName(CORINFO_CLASS_HANDLE, char *, size_t, size_t *)
                // 29: bool isValueClass(CORINFO_CLASS_HANDLE)
                // 2A: uint32_t getClassAttribs(CORINFO_CLASS_HANDLE)
                // 2B: const char * getClassAssemblyName(CORINFO_CLASS_HANDLE)
                // 2C: void * LongLifetimeMalloc(size_t)
                // 2D: void LongLifetimeFree(void *)
                // 2E: bool getIsClassInitedFlagAddress(CORINFO_CLASS_HANDLE, CORINFO_CONST_LOOKUP *, int *)
                // 2F: void * getClassStaticDynamicInfo(CORINFO_CLASS_HANDLE)
                // 30: void * getClassThreadStaticDynamicInfo(CORINFO_CLASS_HANDLE)
                // 31: bool getStaticBaseAddress(CORINFO_CLASS_HANDLE, bool, CORINFO_CONST_LOOKUP *)
                // 32: unsigned int getClassSize(CORINFO_CLASS_HANDLE)
                // 33: unsigned int getHeapClassSize(CORINFO_CLASS_HANDLE)
                // 34: bool canAllocateOnStack(CORINFO_CLASS_HANDLE)
                // 35: unsigned int getClassAlignmentRequirement(CORINFO_CLASS_HANDLE, bool)
                // 36: unsigned int getClassGClayout(CORINFO_CLASS_HANDLE, uint8_t *)
                // 37: unsigned int getClassNumInstanceFields(CORINFO_CLASS_HANDLE)
                // 38: CORINFO_FIELD_HANDLE getFieldInClass(CORINFO_CLASS_HANDLE, int32_t)
                // 39: GetTypeLayoutResult getTypeLayout(CORINFO_CLASS_HANDLE, CORINFO_TYPE_LAYOUT_NODE *, size_t *)
                // 3A: bool checkMethodModifier(CORINFO_METHOD_HANDLE, const char *, bool)
                // 3B: CorInfoHelpFunc getNewHelper(CORINFO_CLASS_HANDLE, bool *)
                // 3C: CorInfoHelpFunc getNewArrHelper(CORINFO_CLASS_HANDLE)
                // 3D: CorInfoHelpFunc getCastingHelper(CORINFO_RESOLVED_TOKEN *, bool)
                // 3E: CorInfoHelpFunc getSharedCCtorHelper(CORINFO_CLASS_HANDLE)
                // 3F: CORINFO_CLASS_HANDLE getTypeForBox(CORINFO_CLASS_HANDLE)
                // 40: CorInfoHelpFunc getBoxHelper(CORINFO_CLASS_HANDLE)
                // 41: CorInfoHelpFunc getUnBoxHelper(CORINFO_CLASS_HANDLE)
                // 42: CORINFO_OBJECT_HANDLE getRuntimeTypePointer(CORINFO_CLASS_HANDLE)
                // 43: bool isObjectImmutable(CORINFO_OBJECT_HANDLE)
                // 44: bool getStringChar(CORINFO_OBJECT_HANDLE, int, uint16_t *)
                // 45: CORINFO_CLASS_HANDLE getObjectType(CORINFO_OBJECT_HANDLE)
                // 46: bool getReadyToRunHelper(CORINFO_RESOLVED_TOKEN *, CorInfoHelpFunc, CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *)
                // 47: void getReadyToRunDelegateCtorHelper(CORINFO_RESOLVED_TOKEN *, mdToken, CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_LOOKUP *)
                // 48: CorInfoInitClassResult initClass(CORINFO_FIELD_HANDLE, CORINFO_METHOD_HANDLE, CORINFO_CONTEXT_HANDLE)
                // 49: void classMustBeLoadedBeforeCodeIsRun(CORINFO_CLASS_HANDLE)
                // 4A: CORINFO_CLASS_HANDLE getBuiltinClass(CorInfoClassId)
                // 4B: CorInfoType getTypeForPrimitiveValueClass(CORINFO_CLASS_HANDLE)
                // 4C: CorInfoType getTypeForPrimitiveNumericClass(CORINFO_CLASS_HANDLE)
                // 4D: bool canCast(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 4E: TypeCompareState compareTypesForCast(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 4F: TypeCompareState compareTypesForEquality(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 50: bool isMoreSpecificType(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE)
                // 51: bool isExactType(CORINFO_CLASS_HANDLE)
                // 52: TypeCompareState isGenericType(CORINFO_CLASS_HANDLE)
                // 53: TypeCompareState isNullableType(CORINFO_CLASS_HANDLE)
                // 54: TypeCompareState isEnum(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE *)
                // 55: CORINFO_CLASS_HANDLE getParentType(CORINFO_CLASS_HANDLE)
                // 56: CorInfoType getChildType(CORINFO_CLASS_HANDLE, CORINFO_CLASS_HANDLE *)
                // 57: bool isSDArray(CORINFO_CLASS_HANDLE)
                // 58: unsigned int getArrayRank(CORINFO_CLASS_HANDLE)
                // 59: CorInfoArrayIntrinsic getArrayIntrinsicID(CORINFO_METHOD_HANDLE)
                // 5A: void * getArrayInitializationData(CORINFO_FIELD_HANDLE, uint32_t)
                // 5B: CorInfoIsAccessAllowedResult canAccessClass(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_HELPER_DESC *)
                // 5C: size_t printFieldName(CORINFO_FIELD_HANDLE, char *, size_t, size_t *)
                // 5D: CORINFO_CLASS_HANDLE getFieldClass(CORINFO_FIELD_HANDLE)
                // 5E: CorInfoType getFieldType(CORINFO_FIELD_HANDLE, CORINFO_CLASS_HANDLE *, CORINFO_CLASS_HANDLE)
                // 5F: unsigned int getFieldOffset(CORINFO_FIELD_HANDLE)
                // 60: void getFieldInfo(CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_ACCESS_FLAGS, CORINFO_FIELD_INFO *)
                // 61: uint32_t getThreadLocalFieldInfo(CORINFO_FIELD_HANDLE, bool)
                // 62: void getThreadLocalStaticBlocksInfo(CORINFO_THREAD_STATIC_BLOCKS_INFO *)
                // 63: void getThreadLocalStaticInfo_NativeAOT(CORINFO_THREAD_STATIC_INFO_NATIVEAOT *)
                // 64: bool isFieldStatic(CORINFO_FIELD_HANDLE)
                // 65: int getArrayOrStringLength(CORINFO_OBJECT_HANDLE)
                // 66: void getBoundaries(CORINFO_METHOD_HANDLE, unsigned int *, uint32_t **, ICorDebugInfo::BoundaryTypes *)
                // 67: void setBoundaries(CORINFO_METHOD_HANDLE, uint32_t, ICorDebugInfo::OffsetMapping *)
                // 68: void getVars(CORINFO_METHOD_HANDLE, uint32_t *, ICorDebugInfo::ILVarInfo **, bool *)
                // 69: void setVars(CORINFO_METHOD_HANDLE, uint32_t, ICorDebugInfo::NativeVarInfo *)
                // 6A: void reportRichMappings(ICorDebugInfo::InlineTreeNode *, uint32_t, ICorDebugInfo::RichOffsetMapping *, uint32_t)
                // 6B: void reportAsyncDebugInfo(ICorDebugInfo::AsyncInfo *, ICorDebugInfo::AsyncSuspensionPoint *, ICorDebugInfo::AsyncContinuationVarInfo *, uint32_t)
                // 6C: void reportMetadata(const char *, const void *, size_t)
                // 6D: void * allocateArray(size_t)
                // 6E: void freeArray(void *)
                // 6F: CORINFO_ARG_LIST_HANDLE getArgNext(CORINFO_ARG_LIST_HANDLE)
                // 70: CorInfoTypeWithMod getArgType(CORINFO_SIG_INFO *, CORINFO_ARG_LIST_HANDLE, CORINFO_CLASS_HANDLE *)
                // 71: int getExactClasses(CORINFO_CLASS_HANDLE, int, CORINFO_CLASS_HANDLE *)
                // 72: CORINFO_CLASS_HANDLE getArgClass(CORINFO_SIG_INFO *, CORINFO_ARG_LIST_HANDLE)
                // 73: CorInfoHFAElemType getHFAType(CORINFO_CLASS_HANDLE)
                // 74: bool runWithErrorTrap(errorTrapFunction, void *)
                // 75: bool runWithSPMIErrorTrap(errorTrapFunction, void *)
                // 76: void getEEInfo(CORINFO_EE_INFO *)
                // 77: void getAsyncInfo(CORINFO_ASYNC_INFO *)
                // 78: CORINFO_METHOD_HANDLE getAwaitReturnCall(CORINFO_METHOD_HANDLE, CORINFO_CONTEXT_HANDLE *, CORINFO_LOOKUP *)
                // 79: mdMethodDef getMethodDefFromMethod(CORINFO_METHOD_HANDLE)
                // 7A: size_t printMethodName(CORINFO_METHOD_HANDLE, char *, size_t, size_t *)
                // 7B: const char * getMethodNameFromMetadata(CORINFO_METHOD_HANDLE, const char **, const char **, const char **, size_t)
                // 7C: unsigned int getMethodHash(CORINFO_METHOD_HANDLE)
                // 7D: bool getSystemVAmd64PassStructInRegisterDescriptor(CORINFO_CLASS_HANDLE, SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR *)
                // 7E: void getSwiftLowering(CORINFO_CLASS_HANDLE, CORINFO_SWIFT_LOWERING *)
                // 7F: void getFpStructLowering(CORINFO_CLASS_HANDLE, CORINFO_FPSTRUCT_LOWERING *)
                // 80: CorInfoWasmType getWasmLowering(CORINFO_CLASS_HANDLE)
                // 81: uint32_t getAddressAlignment(void *)
                // 82: void getWasmWellKnownGlobals(CORINFO_WASM_WELLKNOWN_GLOBALS *)
                //
                // src\coreclr\inc\corinfo.h
                // class ICorDynamicInfo
                // 83: uint32_t getThreadTLSIndex(void **)
                // 84: int32_t * getAddrOfCaptureThreadGlobal(void **)
                // 85: void getHelperFtn(CorInfoHelpFunc, CORINFO_CONST_LOOKUP *, CORINFO_METHOD_HANDLE *)
                // 86: void getFunctionEntryPoint(CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *, CORINFO_ACCESS_FLAGS)
                // 87: void getFunctionFixedEntryPoint(CORINFO_METHOD_HANDLE, bool, CORINFO_CONST_LOOKUP *)
                // 88: CORINFO_MODULE_HANDLE embedModuleHandle(CORINFO_MODULE_HANDLE, void **)
                // 89: CORINFO_CLASS_HANDLE embedClassHandle(CORINFO_CLASS_HANDLE, void **)
                // 8A: CORINFO_METHOD_HANDLE embedMethodHandle(CORINFO_METHOD_HANDLE, void **)
                // 8B: CORINFO_FIELD_HANDLE embedFieldHandle(CORINFO_FIELD_HANDLE, void **)
                // 8C: void embedGenericHandle(CORINFO_RESOLVED_TOKEN *, bool, CORINFO_METHOD_HANDLE, CORINFO_GENERICHANDLE_RESULT *)
                // 8D: void getLocationOfThisType(CORINFO_METHOD_HANDLE, CORINFO_LOOKUP_KIND *)
                // 8E: void getAddressOfPInvokeTarget(CORINFO_METHOD_HANDLE, CORINFO_CONST_LOOKUP *)
                // 8F: void * GetCookieForPInvokeCalliSig(CORINFO_SIG_INFO *, void **)
                // 90: void * GetCookieForInterpreterCalliSig(CORINFO_SIG_INFO *)
                // 91: CORINFO_JUST_MY_CODE_HANDLE getJustMyCodeHandle(CORINFO_METHOD_HANDLE, CORINFO_JUST_MY_CODE_HANDLE **)
                // 92: void GetProfilingHandle(bool *, void **, bool *)
                // 93: void getCallInfo(CORINFO_RESOLVED_TOKEN *, CORINFO_RESOLVED_TOKEN *, CORINFO_METHOD_HANDLE, CORINFO_CALLINFO_FLAGS, CORINFO_CALL_INFO *)
                // 94: bool getStaticFieldContent(CORINFO_FIELD_HANDLE, uint8_t *, int, int, bool)
                // 95: bool getObjectContent(CORINFO_OBJECT_HANDLE, uint8_t *, int, int)
                // 96: CORINFO_CLASS_HANDLE getStaticFieldCurrentClass(CORINFO_FIELD_HANDLE, bool *)
                // 97: CORINFO_VARARGS_HANDLE getVarArgsHandle(CORINFO_SIG_INFO *, CORINFO_METHOD_HANDLE, void **)
                // 98: InfoAccessType constructStringLiteral(CORINFO_MODULE_HANDLE, mdToken, void **)
                // 99: InfoAccessType emptyStringLiteral(void **)
                // 9A: uint32_t getFieldThreadLocalStoreID(CORINFO_FIELD_HANDLE, void **)
                // 9B: CORINFO_METHOD_HANDLE GetDelegateCtor(CORINFO_METHOD_HANDLE, CORINFO_CLASS_HANDLE, CORINFO_METHOD_HANDLE, DelegateCtorArgs *)
                // 9C: void MethodCompileComplete(CORINFO_METHOD_HANDLE)
                // 9D: bool getTailCallHelpers(CORINFO_RESOLVED_TOKEN *, CORINFO_SIG_INFO *, CORINFO_GET_TAILCALL_HELPERS_FLAGS, CORINFO_TAILCALL_HELPERS *)
                // 9E: CORINFO_METHOD_HANDLE getAsyncResumptionStub(void **)
                // 9F: CORINFO_CLASS_HANDLE getContinuationType(size_t, bool *, size_t)
                // A0: bool convertPInvokeCalliToCall(CORINFO_RESOLVED_TOKEN *, bool)
                // A1: bool notifyInstructionSetUsage(CORINFO_InstructionSet, bool)
                // A2: void updateEntryPointForTailCall(CORINFO_CONST_LOOKUP *)
                // A3: CORINFO_WASM_TYPE_SYMBOL_HANDLE getWasmTypeSymbol(CorInfoWasmType *, size_t)
                // A4: CORINFO_METHOD_HANDLE getSpecialCopyHelper(CORINFO_CLASS_HANDLE)
                //
                // src\coreclr\inc\corjit.h
                // class ICorJitInfo
                // A5: void allocMem(AllocMemArgs *)
                public const int AllocMemIndex = 0xA5;
                // A6: void reserveUnwindInfo(bool, bool, uint32_t)
                // A7: void allocUnwindInfo(uint8_t *, uint8_t *, uint32_t, uint32_t, uint32_t, uint8_t *, CorJitFuncKind)
                // A8: void * allocGCInfo(size_t)
                // A9: void setEHcount(unsigned int)
                // AA: void setEHinfo(unsigned int, const CORINFO_EH_CLAUSE *)
                // AB: bool logMsg(unsigned int, const char *, va_list)
                // AC: int doAssert(const char *, int, const char *)
                // AD: void reportFatalError(CorJitResult)
                // AE: JITINTERFACE_HRESULT getPgoInstrumentationResults(CORINFO_METHOD_HANDLE, PgoInstrumentationSchema **, uint32_t *, uint8_t **, PgoSource *, bool *)
                // AF: JITINTERFACE_HRESULT allocPgoInstrumentationBySchema(CORINFO_METHOD_HANDLE, PgoInstrumentationSchema *, uint32_t, uint8_t **)
                // B0: void recordCallSite(uint32_t, CORINFO_SIG_INFO *, CORINFO_METHOD_HANDLE)
                // B1: void recordWasmManagedCallSig(CORINFO_SIG_INFO *)
                // B2: void recordRelocation(void *, void *, void *, CorInfoReloc, int32_t)
                // B3: CorInfoReloc getRelocTypeHint(void *)
                // B4: uint32_t getExpectedTargetArchitecture()
                // B5: uint32_t getJitFlags(CORJIT_FLAGS *, uint32_t)

                public const int TotalVtableCount = 0xB6;
            }

            // src/coreclr/inc/corjit.h AllocMemChunk / AllocMemArgs
            // AllocMemArgs is a chunk list (hot/cold/readonly), not the older flat layout.
            [Flags]
            public enum CorJitAllocMemFlag : uint
            {
                HotCode = 1,
                ColdCode = 2,
                ReadonlyData = 4,
                HasPointersToCode = 8,
            }

            [StructLayout(LayoutKind.Sequential)]
            public struct AllocMemChunk
            {
                public uint alignment;
                public uint size;
                public CorJitAllocMemFlag flags;
                public IntPtr block;
                public IntPtr blockRW;
            }

            [StructLayout(LayoutKind.Sequential)]
            public new struct AllocMemArgs
            {
                public AllocMemChunk* chunks;
                public uint chunksCount;
                public uint xcptnsCount;
            }

            [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
            public new delegate void AllocMemDelegate(
                IntPtr thisPtr, // ICorJitInfo*
                AllocMemArgs* args
            );

            public new readonly struct InvokeAllocMemPtr
            {
                private readonly IntPtr methodPtr;

                public InvokeAllocMemPtr(delegate*<IntPtr, IntPtr, AllocMemArgs*, void> ptr)
                {
                    methodPtr = (IntPtr)ptr;
                }

                public delegate*<IntPtr, IntPtr, AllocMemArgs*, void> InvokeAllocMem
                    => (delegate*<IntPtr, IntPtr, AllocMemArgs*, void>)methodPtr;
            }

            public static new InvokeAllocMemPtr InvokeAllocMemFn => new(&InvokeAllocMem);

            public static new void InvokeAllocMem(
                IntPtr functionPtr,
                IntPtr thisPtr,
                AllocMemArgs* args)
            {
                if (functionPtr == IntPtr.Zero)
                    return;

                var fnPtr = (delegate* unmanaged[Thiscall]<IntPtr, AllocMemArgs*, void>)functionPtr;
                fnPtr(thisPtr, args);
            }
        }
    }
}
