// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Memory
	{
		[Flags]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.63-beta+89e7e0c43f")]
		internal enum PAGE_PROTECTION_FLAGS : uint
		{
			PAGE_NOACCESS = 0x00000001,
			PAGE_READONLY = 0x00000002,
			PAGE_READWRITE = 0x00000004,
			PAGE_WRITECOPY = 0x00000008,
			PAGE_EXECUTE = 0x00000010,
			PAGE_EXECUTE_READ = 0x00000020,
			PAGE_EXECUTE_READWRITE = 0x00000040,
			PAGE_EXECUTE_WRITECOPY = 0x00000080,
			PAGE_GUARD = 0x00000100,
			PAGE_NOCACHE = 0x00000200,
			PAGE_WRITECOMBINE = 0x00000400,
			PAGE_GRAPHICS_NOACCESS = 0x00000800,
			PAGE_GRAPHICS_READONLY = 0x00001000,
			PAGE_GRAPHICS_READWRITE = 0x00002000,
			PAGE_GRAPHICS_EXECUTE = 0x00004000,
			PAGE_GRAPHICS_EXECUTE_READ = 0x00008000,
			PAGE_GRAPHICS_EXECUTE_READWRITE = 0x00010000,
			PAGE_GRAPHICS_COHERENT = 0x00020000,
			PAGE_GRAPHICS_NOCACHE = 0x00040000,
			PAGE_ENCLAVE_THREAD_CONTROL = 0x80000000,
			PAGE_REVERT_TO_FILE_MAP = 0x80000000,
			PAGE_TARGETS_NO_UPDATE = 0x40000000,
			PAGE_TARGETS_INVALID = 0x40000000,
			PAGE_ENCLAVE_UNVALIDATED = 0x20000000,
			PAGE_ENCLAVE_MASK = 0x10000000,
			PAGE_ENCLAVE_DECOMMIT = 0x10000000,
			PAGE_ENCLAVE_SS_FIRST = 0x10000001,
			PAGE_ENCLAVE_SS_REST = 0x10000002,
			SEC_PARTITION_OWNER_HANDLE = 0x00040000,
			SEC_64K_PAGES = 0x00080000,
			SEC_FILE = 0x00800000,
			SEC_IMAGE = 0x01000000,
			SEC_PROTECTED_IMAGE = 0x02000000,
			SEC_RESERVE = 0x04000000,
			SEC_COMMIT = 0x08000000,
			SEC_NOCACHE = 0x10000000,
			SEC_WRITECOMBINE = 0x40000000,
			SEC_LARGE_PAGES = 0x80000000,
			SEC_IMAGE_NO_EXECUTE = 0x11000000,
		}
	}
}
