using System;

namespace MonoMod {
    /// <summary>
    /// MonoMod replace attribute.
    /// Apply it onto a method and no orig_ method will be generated by MonoMod.
    /// Apply it onto a field and its attributes and field type will be replaced.
    /// Apply it onto a property and it will be removed first, as if you're just adding your own.
    /// Apply it onto a type and the original type will be removed first.
    /// </summary>
    [MonoMod__SafeToCopy__]
    public class MonoModReplace : Attribute {
    }
}

