using System;

namespace MonoMod {
    [MonoModIgnore]
    /// <summary>
    /// MonoMod replace attribute.
    /// Apply it onto a method and no orig_ method will be generated by MonoMod.
    /// </summary>
    public class MonoModReplace : Attribute {
    }
}

